### ISSUE TITLE
Need support for console.log

### ISSUE THREAD

**Issue by siddharthroy12** [mode777/rayjs#1]
Trying to use `console.log` crashes the game

![image](https://github.com/mode777/rayjs/assets/46083528/d532d81b-73d4-4f2b-8bcf-aa1ab719676c)

**Comment by mode777** [comment]
Yeah I noticed that too thats why I added it back in yesterday (77cebb3dce6ab3db68363b3cfccbb79bf3a0bf65). If you don't want to wait for the next release and don't want to build yourself, you can use `traceLog(LOG_INFO, "My log message")` as a workaround.
